### ISSUE TITLE
Request: Add Analyze command

### ISSUE THREAD

**Issue by DutchyOven** [dantebarba/autoscan-adapter#3]
I know this does a refresh using plexapi but I was wondering is there anyway you could add analyze() as well or as an option? I use Tdarr to add a new aac track and unless I rename the file autoscan, nor autoscan adapter can tell it to reanalyze the file.

**Comment by frasderp** [comment]
Would love this... having same issue as OP.

**Comment by frasderp** [comment]
After a bit of research, the Analyze function is not available through the web API calls at the moment (refresh metadata, and scan are however).

Analyze can however be called locally through the Plex Media Scanner API, so this might be an option with someone more familiar.

I have setup a daily cronjob to do a full analyze of the library... not exactly efficient but it keeps it clean.

**Comment by jrcalvert** [comment]
This does seem to work if I add "element.analyze()" into your refresh_metadata function.

**Comment by dantebarba** [comment]
The analyze process would add some additional I/O so I'll include the option using an env var so users can decide if they want to activate it or not. 

Should the analysis be performed before or after the refresh? Just as reference the place to add the analyze command would be before or after this line:

https://github.com/dantebarba/autoscan-adapter/blob/fd51564944bc97c2c716b000aa229b687913cabd/plexapihandler.py#L74

**Comment by DutchyOven** [comment]
I feel like it should be after refresh.

**Comment by jrcalvert** [comment]
Yes I agree - after refresh feels right!

**Comment by dantebarba** [comment]
hi y'all

@DutchyOven @frasderp @jrcalvert I created a PR which should add the analyze feature. You have to setup the "ANALYZE_MEDIA" env var and you should be good to go.

I don't have the time to test it right now so I'll let you guys test the PR for a couple of days. You can checkout the branch at https://github.com/dantebarba/autoscan-adapter/tree/feature/add-analyze-option and use the Dockerfile to build the updated version in your local machine.

**Comment by DutchyOven** [comment]
Lovely! I’ll set it up tonight and test it over the weekend.

**Comment by DutchyOven** [comment]
> hi y'all
> 
> @DutchyOven @frasderp @jrcalvert I created a PR which should add the analyze feature. You have to setup the "ANALYZE_MEDIA" env var and you should be good to go.
> 
> I don't have the time to test it right now so I'll let you guys test the PR for a couple of days. You can checkout the branch at https://github.com/dantebarba/autoscan-adapter/tree/feature/add-analyze-option and use the Dockerfile to build the updated version in your local machine.

If anyone else here got it up and running using compose let me know. I’m new at building from dockerfile locally so I’ll give it another go in the morning.

**Comment by jrcalvert** [comment]
Hello - I have just tried this but unfortunately are getting the below error:
`Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/usr/local/lib/python3.11/site-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.11/site-packages/werkzeug/urls.py)
`

**Comment by DutchyOven** [comment]
Yep same error.

**Comment by dantebarba** [comment]
Done guys. Just pull the changes from the branch and rebuild the dockerfile.

**Comment by DutchyOven** [comment]
> Done guys. Just pull the changes from the branch and rebuild the dockerfile.

got it up and running, nice I'll start testing now

**Comment by jrcalvert** [comment]
Yes, I have it running now also, All looking good thanks!

**Comment by DutchyOven** [comment]
It's been running all night and from what I can tell its working great. Everything Tdarr adds a new audio track to has been analyzed and the track shows up as default.

**Comment by dantebarba** [comment]
Version 0.2.0 was released. I'm closing this, in case you need to report anything just open a new issue. Thanks!
